### ISSUE TITLE
Is bat_filter_month_form used?

### ISSUE THREAD

**Issue by acrollet** [Roomify/bat_drupal#1]
@istos @nicolocaruso85 I don't see it used anywhere in the bat codebase or indeed in the roomify distro - is it necessary?

**Comment by acrollet** [comment]
same question for bat_element_validate_integer_zero_positive() and bat_element_validate_integer_positive_less_than_100()

**Comment by istos** [comment]
Yup - these are leftovers from the Rooms code. We can remove them

**Comment by acrollet** [comment]
I removed bat_element_validate_integer_zero_positive - nb I also removed bat_range, don't see any references to it either.
