### ISSUE TITLE
Create New State - Color Widget

### ISSUE THREAD

**Issue by simmonspaul** [Roomify/bat_drupal#14]
low impact item, cosmetic, easily worked around.

When creating a new state, and one gets to selecting a color (the default is #000000).
If you click the outer band of the color widget, the the color value default does not change.

It is only when you click within the square of the widget that the color widget becomes activated and then properly populates that color value. You can then go to the outer band if you wish and change the color.

**Comment by istos** [comment]
This is the default behavior of the widget for Drupal so the issue should be taken up with the implementation of the color widget.
