### ISSUE TITLE
Can a max quota be placed on Unit capacity?

### ISSUE THREAD

**Issue by qcutter** [Roomify/bat_drupal#17]
My use case is that I will have members creating bookings and will need to have a quota set on the capacity that the will be able to create. Is this possible ?

**Comment by acrollet** [comment]
Hi @qcutter,

this is certainly possible - you could do this in the Drupal layer in various ways, or you could implement a BAT [Constraint](https://github.com/Roomify/bat/tree/master/src/Constraint) to prevent users from seeing availability when they are trying to book a resource. Development for bat_drupal is still moving quickly and we hope to have more Drupal infrastructure in place around bookings in the next few days, so it may be best to hang tight for a bit.

**Comment by qcutter** [comment]
sure, I hope I explained correctly, but what I was referring to is say I have a unit type where I want people to only create a set number of units (ie a single booking unit, or a 65 capacity theater). If I understand the way this solution works there is a 1 to 1 relationship between a booking and booking time slot. So if I run a barber shop and have 10 chairs, I would need 10 booking "units". If thats the case then being able to configure the number of units that can be created would be very essential to constraining different use cases. Thank you for the update. I am and will continue to follow this. I face two use cases i would like to use this module for (Booking locations, and selling tickets).
