### ISSUE TITLE
Incorrect error handling when no unit bundles have been added

### ISSUE THREAD

**Issue by simmonspaul** [Roomify/bat_drupal#18]
In the situation where no unit bundles have been added.

If you go into Unit Management and then try to add a unit, this is error captured.
However the message that is displayed advises that you must add a type bundle (with a hyperlink to add a type bundle)

**Comment by acrollet** [comment]
Hi there,

I'm not sure how to reproduce this issue, could you expand? We create a unit bundle automatically upon installation, are you referring to a Type bundle?

**Comment by simmonspaul** [comment]
(I apologise for the brain deadness of this scenario. 
Realise that I was flattening everything several times during testing...)

I deleted the unit bundle that you automatically created.
Then if you you go to "unit management" and try to add a unit you get:
"Type cannot be added because you have not created any Type bundles yet. Go to the type bundle creation page to add a new type type."

I have type bundles... I don't have unit bundles...

**Comment by acrollet** [comment]
I believe this falls under "not using as designed" :)
