### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by simmonspaul** [Roomify/bat_drupal#19]
The module Field_UI is required.

Bat_API has a dependency on rooms_availability in order to be activated.
Therefore the rooms module (which contains rooms_availability) needs to be installed.

**Comment by acrollet** [comment]
rooms_availability is required by bat_api 7.x-1.x, but not 7.x-2.x. Please ensure you're using bat_api 7.x-2.x with bat_drupal

thanks,
Adrian

**Comment by simmonspaul** [comment]
Just to clarify. I had originally used drush to install bat_api (without specifying version), then git cloned and managed the 7.x-2.x code pulls directly from the underlying directory. I uninstalled and reinstalled the module from the panel, and the new info file was pulled into the drupal install properly representing the code I was using.
