### ISSUE TITLE
Environmental Requirements

### ISSUE THREAD

**Issue by simmonspaul** [Roomify/bat_drupal#20]
I am having environment configuration issues that have nothing to do with BAT per say but which might cause issues for potential BAT users.

I have spent some time going through this systematically and trying various patches to resolve.

Before installing BAT at all. 
I am trying to get FullCalendar working. 
I am on Drupal 7.41. I have installed FullCalendar Version 7.x-2.0.
The scenario below is for FullCalendar library plugin 1.5.4 & 1.6.7.
I am using firefox browser v 43.0.4.

I add a date field to a node and create a FullCalendar view.
The calendar will only show up when I click on "update preview". When I refresh the page the calendar disappears. When I go to the node page for the view itself, the calendar doesn't show.
   I have gone through the FullCalendar issue log and https://www.drupal.org/node/2323445 - there is a known issue with embedded views. I tried working with the provided patch but no joy.

Using IE 11.0.8 I get the same result as above except on the node page the calendar shows up.
**\* I am getting a strong feeling that FullCalendar does not support FireFox. Since that was my primary browser, it is the first explanation for my testing of BAT not displaying the calendar. ***

When I change the FullCalendar library plugin to version 2.6.0. (I also have the moment library available). Then the calendar does not show up in the view any longer, not on an "update preview" or on the node itself, using either browser.
**\* Please consider that the later BAT instructions will ask for plugin version 2.6.0 to be installed, meanwhile the FullCalendar module advises that the 2.x series is not supported. Without BAT installed, I can not see a FullCalendar view on 2.6.0.***

Another requirement for BAT is JQuery update. **\* Again the drupal module has only been tested with 1.5.x and therefore the requirement is taking us into known issue territory. ***

So after I have installed FullCalendar library 2.6.0. Enabled BAT_API 7.x-2.x and all BAT modules. It comes as no surprise that the view I created with FullCalendar does not work in anyway as before.

...
If you guys can share details of your build environment that would be useful.

**Comment by istos** [comment]
Hi - we will be releasing a fully configured BAT Drupal distro for download that will remove many of the questions you are having. I think it would make a lot of sense to wait for that rather than trying lots of different things - BAT is under development so unless you are really confident with Drupal dev you will inevitably run into issues.

**Comment by qcutter** [comment]
But that wont work for existing drupal install base will it? The Distro will only be for fresh installs right?
