### ISSUE TITLE
Error when creating an Event without Units

### ISSUE THREAD

**Issue by derimagia** [Roomify/bat_drupal#22]
When I was first learning the module I couldn't figure this out for a while, but these are the repo steps.

1) Set up module, Type Bundle, Unit Bundle, don't create any units
2) Go to /admin/bat/events/add and create an event
3) Notice the error:

```
Call to a member function getEventDefaultValue on boolean
```

**Comment by acrollet** [comment]
@Derimagia the unit field was not required at one time, but it is now. Please re-open if you can reproduce with the latest versions of bat + bat_api (beta4)

thanks!
