### ISSUE TITLE
Solution Question and Clarification

### ISSUE THREAD

**Issue by qcutter** [Roomify/bat_drupal#23]
BAT questions

Are “ units” the products to be sold (what level do integrate drupal commerce)? if so can states be/also be the products. (use case take a deposit to secure the unit. Then make different payment to move the state of the Unit).If Im selling a ticket and have a price for it to be on hold. If tickets are sent to others for use, that user can make payment for actual state change. Or, user decides to back out the ticket, then no need to reverse payment, just move state back or assign to  next person in a smart que.

Feature Request or clarification, Can we:

-Use Tokens for unit naming convention
-Add Full Day, or default unit time granularity. In cases where the times will be not be configurable or be pre defined, and UI can be simplified to just manipulating the unit or event:state
- ReOrder event:State Order

**Comment by acrollet** [comment]
@qcutter please see the docs at http://docs.roomify.us, there is clarification around integrating commerce/payment solutions. If you would like to follow up with your feature requests, please post them as separate issues, ideally with a complete use case and simple mockup(s).

thanks!
