### ISSUE TITLE
Calender not displaying

### ISSUE THREAD

**Issue by mabo1972** [Roomify/bat_drupal#27]
I've installed the bat php framework with composer and the drupal module 7.x-1.0-beta1 as described. 
All libraries i.e. fullcalender, fullcalender-scheduler and moment are installed.
It looks like all works but when i click on "Manage Availability" in the Unit Management no calendar appears.
What is the reason for this behavior?

For better understanding please take a look at the screencast in the attachment.
[2016-02-03 15h10_18.zip](https://github.com/Roomify/bat_drupal/files/115770/2016-02-03.15h10_18.zip)

**Comment by cecrs** [comment]
Is the roomify/bat package installed?  (admin/config/system/composer-manager)

**Comment by mabo1972** [comment]
Yes

![2016-02-04_07h41_03](https://cloud.githubusercontent.com/assets/8982685/12807840/cd49a6d2-cb12-11e5-9e1b-2b1904d8fdb3.png)

and jquery is = 1.10

![2016-02-04_07h46_08](https://cloud.githubusercontent.com/assets/8982685/12807928/7fb860d8-cb13-11e5-9fdc-7264ca23a77d.png)

**Comment by istos** [comment]
Hi mabo1972 - if you have the BAT API module, jquery at 1.10 and the BAT library all installed have a look in Reports and the Drupal log if any issues are coming up as well as Javascript errors in the browser tools console.

**Comment by mabo1972** [comment]
Hi istos,
there were no errors in drupal log but a few javascript errors in the browser tools console. (screenshot)
![2016-02-04_11h55_50](https://cloud.githubusercontent.com/assets/8982685/12813154/7ca6bc8c-cb36-11e5-8fdb-607e6dec0246.png)

**Comment by istos** [comment]
You should re-check how you added the FullCalendar and Moment libraries - they seem to be missing.

**Comment by mabo1972** [comment]
According to status report everything is installed.

![2016-02-04_12h03_20](https://cloud.githubusercontent.com/assets/8982685/12813304/7c897ae0-cb37-11e5-83d1-fda5e349d140.png)

**Comment by istos** [comment]
Yup it does look that way. Must be some environment-specific issue. Not sure how we can help, not something we have seen before. If you can provide steps to reliably reproduce then we might try and dig further into it.

**Comment by mabo1972** [comment]
I run the page in a boa environment. [github.com/omega8cc/boa](https://github.com/omega8cc/boa). 
I try my luck in another environment such as devdesktop.

**Comment by mabo1972** [comment]
I've installed drupal with bat in aquia dev-desktop in the same way as before and it works. Seems like that i make an error in the previous installation.

Thank you very much for your effort
