### ISSUE TITLE
Themeing Display, Add, and Edit pages

### ISSUE THREAD

**Issue by qcutter** [Roomify/bat_drupal#29]
Im not sure, so this is a friendly question. How would we theme any of this?? Because all of the edit paths goes through /admin, everything is using drupals admin theme. The admin theme is ok for me but the entity add, edit, and display should be able to be themed via tpl.php, Display suite, or panels. I cant get anything to show through normal means (expect admin pathed functionality). Can someone post how to theme these as it dont seem to follow normal drupal entity theming (also hard to find and figure out)

**Comment by istos** [comment]
What are you trying to show qcutter? I am pretty sure these things can be themed by panels, display suite or tpl because we've done it ;-)
