### ISSUE TITLE
general question for implementation and construction

### ISSUE THREAD

**Issue by mabo1972** [Roomify/bat_drupal#30]
I want to create a page to manage bookings for dive safaris.
There are several boats with different number of cabins. There are always complete tours offered which usually take one week.

I have the boats, different tours (northtour, southtour, wrecktour,...), different rooms per boat (suite, royal suite,...), different states (available, reserved, booked)

My problem is the defnition. Is the Tour now to create as an event? Is the room a unit or a type?

What is the best way to realize this in bat_drupal

I'm grateful for any help

**Comment by acrollet** [comment]
Hi @mabo1972, 

that's an interesting use case. The beauty and the difficulty of BAT is that it's quite generic, so doing this is possible, but will take some work on your part. You might try creating types for each tour/room type combination. (e.g. north tour S.S. Minnow Royal Suite, with as many units as there are suites on the S.S. Minnow) You could then make those units available only when there will be a tour, and add some front end logic to ensure that users can only pick valid start and end dates.

FYI we are planning on releasing a BAT tours product sometime in the next few weeks that should help simplify some of these considerations. Please consider signing up for our mailing list at https://roomify.us

good luck!
