### ISSUE TITLE
Can't get Calendar to display

### ISSUE THREAD

**Issue by kernel-suave** [Roomify/bat_drupal#31]
Greetings!

I have installed BAT and the BAT API modules, have everything installed in Composer Manger correctly, and have placed the moment, fullcalendar, and fullcalendar-scheduler into the all/libraries folder.  I am running jQuery = 1.10, with a clean install of Drupal 7.42, (modules insatlled in this order: date, date API, date popup, jQuery update, variable, x-autoload, services, Chaos tools, REST server, entity API, views bulk operations, views megarow, rooms availability, rooms unit, rooms, rooms UI, BAT tools API, BAT unit, BAT event, BAT event UI, BAT fullcalendar)

Clicking on the Unit Management shows a list of bundles, but no calendar option.

I don't know if it's related, but when I go to the Configuration page or Status Report page, I receive the following error messages:

Warning: strcasecmp() expects parameter 2 to be string, array given in _system_sort_requirements() (line 2818 of /home/trbirdsall/public_html/Route191.com/modules/system/system.module).
Warning: strcasecmp() expects parameter 2 to be string, array given in _system_sort_requirements() (line 2818 of /home/trbirdsall/public_html/Route191.com/modules/system/system.module).
Warning: strcasecmp() expects parameter 1 to be string, array given in _system_sort_requirements() (line 2818 of /home/trbirdsall/public_html/Route191.com/modules/system/system.module).
Warning: strcasecmp() expects parameter 2 to be string, array given in _system_sort_requirements() (line 2818 of /home/trbirdsall/public_html/Route191.com/modules/system/system.module).
Warning: usort(): Array was modified by the user comparison function in system_status() (line 2335 of /home/trbirdsall/public_html/Route191.com/modules/system/system.admin.inc).

Also there is a Warning message on the Status page that is simply labeled "Array, Array".

Thanks in advance!

**Comment by istos** [comment]
A calendar option will show up once you have created an event type and a unit type. We need to write this documentation up but in the meantime your best bet is to follow this screencast: https://vimeo.com/151918276

**Comment by kernel-suave** [comment]
I believe I've got that correct; so far I have defined type bundles, unit bundles, types, and units.  

![image](https://cloud.githubusercontent.com/assets/17087975/12855657/e7724b54-cbfd-11e5-9da0-ea8e67bb2e9b.png)

**Comment by istos** [comment]
Looks like you are missing the unit type there. You should create units using the interface within Unit Types to make sure they get connected not from Unit Management (we will be removing that to avoid confusion)

**Comment by kernel-suave** [comment]
I apologize, I'm still confused.  What do you mean 'within Unit Types'?

**Comment by istos** [comment]
Go to admin/bat/unit-management where you should see your unit types, click on manage units and create a unit from there. 

The calendar options will show up once you have Types which define their default fields for event values  (in admin/bat/config/type-bundles/manage/<unit type>

**Comment by kernel-suave** [comment]
Thanks so much for all your help!  I'm making an attempt at starting over with setting up everything.  

Trying to delete the event reference above that has no unit type, I receive these errors: 

Warning: array_flip(): Can only flip STRING and INTEGER values! in EntityAPIController->load() (line 219 of /home/trbirdsall/public_html/Route191.com/sites/all/modules/entity/includes/entity.controller.inc).

Then:

Fatal error: Call to a member function getEventDefaultValue() on a non-object in /home/trbirdsall/public_html/Route191.com/sites/all/modules/bat/modules/bat_unit/bat_unit.module on line 858

I do have unit types defined, and when I try to just add an event with id '2', it just loops saying:

![image](https://cloud.githubusercontent.com/assets/17087975/12873585/4d730df4-cd7e-11e5-97e2-a7fcd428da58.png)

**Comment by kernel-suave** [comment]
BTW, I was able to get rid of the array/array warning and crazy error messages above using Drupal Patch:    core-system_requirements-933684-12.patch (https://www.drupal.org/files/core-system_requirements-933684-12.patch)

**Comment by kernel-suave** [comment]
Update: Simply starting over seemed to work best.  I purged the old tables in SQL, and have been trying to set it all up again. The calendar is showing now (yay!), and I think that I almost have it. I've watched your vimeo ad infinitum, but am still getting stuck adding units.

If i go to admin/bat/config/units, and try to add a new one, I get:

> Units cannot be added because you have not created any unit types yet. Go to the unit type creation page to add a new unit type.  Which leads to:

![image](https://cloud.githubusercontent.com/assets/17087975/12893986/88b32d12-ce51-11e5-9094-6788893a482a.png)

If I go the admin/bat/unit-management > units, and try to add one:

> Type cannot be added because you have not created any Type bundles yet. Go to the type bundle creation page to add a new type type.

![image](https://cloud.githubusercontent.com/assets/17087975/12893775/58c930c0-ce50-11e5-9b45-85ec4ecaa5b2.png)

I have created both unit types, and unit bundles correctly, i believe.

**Comment by kernel-suave** [comment]
Ronald,
I pretty sure that I have figured out my problems: I don't have any unit bundles setup.  I've scoured your new documentation and vimeo, but can't find any reference to unit bundles.  What are these used for, and how should I set them up?
Thanks again!

**Comment by acrollet** [comment]
@TRBirdsall ,

The only reason units have bundles is so that they can be fieldable. BAT creates a default unit bundle on installation. If you find that this doesn't happen on a clean installation with the beta4 versions of bat_drupal, bat_api and the latest beta of the bat library, please re-open this issue and let us know.

thanks!
