### ISSUE TITLE
Default Calendar Lableing specifies Rooms

### ISSUE THREAD

**Issue by qcutter** [Roomify/bat_drupal#33]
Should the Label Refer to the Referencing Type Bundle Name When Categorizing Listed Units? See attached image (i cant get my units to show yet or events to create so, there are no units yet :) )

**Comment by qcutter** [comment]
<img width="1440" alt="screen shot 2016-02-13 at 7 26 24 am" src="https://cloud.githubusercontent.com/assets/114424/13023907/25a2e260-d231-11e5-9021-65eebe11d655.png">

**Comment by qcutter** [comment]
I found the Label I have attachced image of where it is
<img width="445" alt="screen shot 2016-02-13 at 4 08 50 pm" src="https://cloud.githubusercontent.com/assets/114424/13026487/538df990-d26c-11e5-929c-96058decb6de.png">

**Comment by acrollet** [comment]
@qcutter the difficulty here is that we can show Types of more than one Type bundle at once - e.g. Rooms and Activities or the like. Probably the simplest thing to do is to change the text to 'Units' instead of 'Rooms'. 

cc @istos

**Comment by qcutter** [comment]
Yeah, or something generic like "List" or allow the label to be configured or derived using tokens. thx for the reply

**Comment by acrollet** [comment]
Changed to 'Types' - the text can be altered with hook_bat_calendar_settings_alter (resourceLabelText parameter)
