### ISSUE TITLE
Convert Data field to UNIX Timestamp

### ISSUE THREAD

**Issue by derimagia** [Roomify/bat_drupal#34]
The events fields are using 'Date' fields instead of using an int UNIX Timestamp field. What's the main reason for this? It goes against Drupal's standard of fields. 

I'll look into converting them if there isn't a good reason.

**Comment by acrollet** [comment]
@derimagia I'm punting on this one - using datetime represents a change from how we did things in Drupal Rooms, so there was a conscious decision, don't know the reasoning behind it though. Assigning @istos to comment when he's able.

**Comment by derimagia** [comment]
I'm pretty much finishing up the project I was on that used BAT - This actually caused a lot of issues on my end because of timezones - BAT doesn't seem to convert them  to UTC time and stores the info in the database as php's default timezone. If I had to redo it again and I choose to re-use BAT I would convert it to UNIX timestamps at the beginning of the project.
