### ISSUE TITLE
Issues found in latest Merge of pull Request #32

### ISSUE THREAD

**Issue by qcutter** [Roomify/bat_drupal#37]
I know this is not formatted properly. Just making sure I highlight feedback that on that merge 
After the latest Merge of the pull request #32 I found some issues and stated them in the process of conversating about it and placed some info there. Im reposting a link to it here in the hopes it doesn't get over looked and not post everything all over the site:  
https://github.com/Roomify/bat_drupal/commit/5258a5f279fae14deb4a2c08b5655b77c6a31626

**Comment by acrollet** [comment]
@qcutter please try the code in https://github.com/Roomify/bat_drupal/pull/38 and let us know if it resolves the issues.
