### ISSUE TITLE
Drupal 8 usage

### ISSUE THREAD

**Issue by nalipaz** [Roomify/bat_drupal#45]
I saw the description of the github project says Drupal 8 on it. I assume that if it will work in D8 we would have to use custom integrations? What is the status of D8 and is there any documentation on how to get going with BAT and D8?

Thanks

**Comment by nicoknaepen** [comment]
Indeed, what is the atstus of the Drupal 8 port?

**Comment by acrollet** [comment]
I'm afraid the D8 port is currently on hold, with no firm ETA at this time.

**Comment by lalop** [comment]
Is there any progress on this point ? Or can you point us an alternative ?
Thanks

**Comment by acrollet** [comment]
a beta for Drupal 8 support is now available...
