### ISSUE TITLE
Unit availability for each day of week separately

### ISSUE THREAD

**Issue by borisbsu** [Roomify/bat_drupal#49]
I would like to configure unit availability for each day of week separately. 

For example, if someone regularly conducts tours (or so popular experience activities), he may need to have a regular schedule like:
a) Mon. - not available;
b) Tue. - Thu.: available between 11:00 - 15:00;
c) Sat.-Sun.: available between 09:00 - 17:00.

I suppose you thought about such cases before because I see some hardcoded strings in RfA like "single_day_activity_property", "single_day_tour_property", etc.
  
Maybe you can give some ideas how to implement this with BAT?

**Comment by acrollet** [comment]
@borisbsu we've done some different projects around tours, but there tend to be enough different use cases that we haven't been able to publish a generalized solution to the problem. For a use case like you describe, Drupal commerce products with the stock module and a tour date field may suit, along with an interface to make it easy to create the products.
